### ISSUE TITLE
Add an option to set time to change text

### ISSUE THREAD

**Issue by dephraiim** [jayehernandez/letra-extension#347] opened 2020-10-02 22:03 UTC
**Is your feature request related to a problem? Please describe.**
Same text on everytab open. It's not a bug, but it feels always the same unless you refresh for another word.

**Describe the solution you'd like**
An option to set the time range for the word to change or to change it on everytab open or to change it everymidnight.

**Comment by Kvaibhav01** [comment] 2020-10-03 08:47
Hey @dephraiim, this is an intended issue. Please read more about this here. [#273](https://github.com/jayehernandez/letra-extension/issues/273)

**Comment by jayehernandez** [comment] 2020-10-03 10:09
Closing this issue since this is an intended behavior, as pointed out by @Kvaibhav01 as well.

**Closed by jayehernandez** 2020-10-03 10:09 UTC
Labels: enhancement
